
services:

  bioconductor:
    build:
      context: .
      dockerfile: bioconductor_3_16/Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - ./project:/home/gitpod
    environment:
      - USER=gitpod
      - PASSWORD=bioc
